### PR TITLE
Check if document.cookie is available

### LINKED ISSUE #249: JS SDK fails to initialize due to error: "Uncaught SecurityError: Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag"

### PR DESCRIPTION
**Pull request by kamilszostak**
This fixes #249 

I still need to do some testing to validate the SDK works as expected in the `document.cookie` is not accessible. Ideally it should still send all telemetry, but without session and user id.

### CODE REVIEW

File: JavaScript/JavaScriptSDK/Util.ts [hunk 1]
```diff
@@ -258,6 +277,10 @@ module Microsoft.ApplicationInsights {
          * helper method to access userId and sessionId cookie
          */
         public static getCookie(name) {
+            if (!Util.canUseCookies()) {
```
Comment (dnduffy) [inline JavaScript/JavaScriptSDK/Util.ts]: Out of curiosity, can a flag be set at startup rather than making the method call each time?
So "this.canUseCookies" instead of "Util.canUseCookies()"?

**Comment by dnduffy** [comment]
:shipit:

File: JavaScript/JavaScriptSDK/Util.ts (hunk 1 above)
Comment (kamilszostak) [inline JavaScript/JavaScriptSDK/Util.ts]: Good idea. I kept the canUseCookie() method, but I cache the result.

File: JavaScript/JavaScriptSDK/snippet.js [hunk 2]
```diff
@@ -12,7 +12,9 @@
     localDocument.getElementsByTagName(scriptText)[0].parentNode.appendChild(scriptElement);
 
     // capture initial cookie
-    appInsights.cookie = localDocument.cookie;
+    try {
+        appInsights.cookie = localDocument.cookie;
```
Comment (MaxShehovtsov) [inline JavaScript/JavaScriptSDK/snippet.js]: Just wondering if there's a corresponding code that expects/does not expect appInsights.cookie to be unset

**Comment by MaxShehovtsov** [comment]
:shipit:
