### PR TITLE
routes: add ie polyfill for Event constructor

### LINKED ISSUE #998: enableAutoRouteTracking breaks angular router in IE11
To reproduce create a new angular app (ng new my-app), create any component and route to it, and then add application insights. Routing works fine without enableAutoRouteTracking but fails with enableAutoRouteTracking: true with the error "Unhandled Navigation Error:"

Routing works fine with route tracking in Edge, Firefox, and Chrome. This is only an issue in IE11.

Versions:
angular 8.2.2
applicationinsights 2.1.1

### PR DESCRIPTION
**Pull request by markwolff**
Fixes #998 

Adds analytics plugin polyfill for `new Event` so that it can be run in Ie

### CODE REVIEW

File: vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts [hunk 1]
```diff
@@ -92,6 +92,19 @@ export class ApplicationInsights implements IAppInsights, ITelemetryPlugin, IApp
         return config;
     }
 
+    private static _createDomEvent(eventName: string): Event {
```
Comment (hectorhdzg) [inline vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts]: Putting this in a Util class instead would be better

Comment (markwolff) [reply vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts]: Moved to common's `Util`
